site_name: "Miscellaneous LUMI information, tips and tricks"
site_url: https://klust.github.io/LUMI-tips-and-tricks
site_dir: "site/LUMI-tips-and-tricks"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black

nav:
  - Home: index.md
  - Introduction: 00_00_introduction.md
  - Compilers:
    - 01_Compilers/index.md
    - Documentation: 01_Compilers/01_01_Doclinks.md
    - LibSci: 01_Compilers/01_02_LibSci.md
    - Wrapper-induced problems: 01_Compilers/01_03_WrapperIssues.md
    - Miscellaneous topics: 01_Compilers/01_99_misc.md
  - LMOD:
    - 02_LMOD/index.md
    - Dcoumentation: 02_LMOD/02_01_Doclinks.md
    - Lmod setup: 02_LMOD/02_02_LMOD_setup.md
    - PE module structure: 02_LMOD/02_03_PE_module_structure.md
  - Slurm:
    - 03_Slurm/index.md
    - Doc links: 03_Slurm/03_01_Doclinks.md
    - GPU binding: 03_Slurm/03_02_GPU_binding.md
    - Miscellaneous: 03_Slurm/03_99_misc.md
  - AI software:
    - 04_AI_packages/index.md
  - MPI:
    - 05_MPI/index.md
    - Cray MPICH tips&tricks: 05_MPI/05_01_Cray_MPICH_tips.md
    - Open MPI: 05_MPI/05_02_OpenMPI.md
    - OSU micro-benchmarks: 05_MPI/05_03_OSU_benchmarks.md
    - Misc: 05_MPI/05_99_misc.md
  - ROCm:
    - 06_ROCm/index.md
    - Miscellaneous topics: 06_ROCm/06_99_misc.md
  - Lustre:
    - 07_Lustre/index.md
    - Miscellaneous topics: 07_Lustre/07_99_misc.md
  - LUMI-O:
    - 08_LUMI-O/index.md
    - Miscellaneous topics: 08_LUMI-O/08_99_misc.md
  - software:
    - 09_Software/index.md
    - GROMACS: 09_Software/09_G01_GROMACS.md
    - Python: 09_Software/09_P01_Python.md
    - R: 09_Software/09_R01_R.md
  - Linux:
    - 98_Linux/index.md
    - File management: 98_Linux/98_01_File_management.md
    - Bash tips: 98_Linux/98_02_Bash_tips.md
  - Misc:
    - 99_Misc/index.md
    - FLOP computation: 99_Misc/99_01_Flops.md
    - Login node organisation: 99_Misc/99_02_LoginNodes.md
    - HPE software releases: 99_Misc/99_03_SystemEnvironments.md
    - EESSI: 99_Misc/99_04_EESSI.md
    - Energy consumption: 99_Misc/99_05_Energy_consumption.md
  - Doc links from course: Doclinks.md

plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search

markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true
  # Mathematics
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  # add links in bottom right
  social:
    #- type: github
    #  icon: octicons/logo-github
    #  link: https://github.com/klust
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3szWMS7glcfWsEZTZXQ1oQ
