site_name: "Information that is missing or hard to find in the Cray PE manual"
site_url: https://klust.github.io/LUMI-tips-and-tricks
site_dir: "site/LUMI-tips-and-tricks"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black

nav:
  - Home: index.md
  - LMOD:
    - 1_LMOD/index.md
    - Lmod setup: 1_LMOD/1_01_LMOD_setup.md
    - Custom paths: 1_LMOD/1_02_custom_paths.md
  - Compilers:
    - 2_Compilers/index.md
    - Miscellaneous topics: 2_Compilers/2_10_misc.md
  - Slurm:
    - 3_Slurm/index.md
    - Doc links: 3_Slurm/3_01_Doclinks.md
    - Miscellaneous: 3_Slurm/3_10_misc.md
  - AI software:
    - 4_AI_packages/index.md
  - Linux:
    - 9_Linux/index.md
    - Files: 9_01_File_management.md

plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search

markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  # add links in bottom right
  social:
    #- type: github
    #  icon: octicons/logo-github
    #  link: https://github.com/klust
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3szWMS7glcfWsEZTZXQ1oQ
