site_name: "Information that is missing or hard to find in the Cray PE manual"
site_url: https://klust.github.io/LUMI-tips-and-tricks
site_dir: "site/LUMI-tips-and-tricks"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black

nav:
  - Home: index.md
  - Introduction: 00_00_introduction.md
  - Compilers:
    - 01_Compilers/index.md
    - Documentation: 01_Compilers/01_01_Doclinks.md
    - LibSci: 01_Compilers/01_02_LibSci.md
    - Miscellaneous topics: 01_Compilers/01_99_misc.md
  - LMOD:
    - 02_LMOD/index.md
    - Dcoumentation: 02_LMOD/02_01_Doclinks.md
    - Lmod setup: 02_LMOD/02_02_LMOD_setup.md
    - PE module structure: 02_LMOD/02_03_PE_module_structure.md
  - Slurm:
    - 03_Slurm/index.md
    - Doc links: 03_Slurm/03_01_Doclinks.md
    - Miscellaneous: 03_Slurm/03_99_misc.md
  - AI software:
    - 04_AI_packages/index.md
  - MPI:
    - 05_MPI/index.md
    - Cray MPICH tips&tricks: 05_MPI/05_01_Cray_MPICH_tips.md
    - Open MPI: 05_MPI/05_02_OpenMPI.md
    - OSU micro-benchmarks: 05_MPI/05_03_OSU_benchmarks.md
    - Misc: 05_MPI/05_99_misc.md
  - Lustre:
    - 06_Lustre/index.md
    - Miscellaneous topics: 06_Lustre/06_99_misc.md
  - ROCm:
    - 07_ROCm/index.md
    - Miscellaneous topics: 07_ROCm/07_99_misc.md
  - software:
    - 08_Software/index.md
    - GROMACS: 08_Software/08_G01_GROMACS.md
    - Python: 08_Software/08_P01_Python.md
    - R: 08_Software/08_R01_R.md
  - Linux and misc:
    - 99_Linux/index.md
    - File management: 99_Linux/99_01_File_management.md
  - Doc links from course: Doclinks.md

plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search

markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  # add links in bottom right
  social:
    #- type: github
    #  icon: octicons/logo-github
    #  link: https://github.com/klust
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3szWMS7glcfWsEZTZXQ1oQ
